#!/usr/bin/python3
'''
echo '{"inputhash":"648f1f1f7d696316c654c6e6165748bb80a0f6d09be72fcbb081487d7b9fc345","inputcomment":"fdsa"}' | ./hashcheck 
'''

import json
import sys

try:

	data = sys.stdin.read()

	params = json.loads(data)
	if "inputhash" not in params:
		raise Exception("no hash in request")

	hashid = params["inputhash"] 
	# формат файла info.txt 
	# что мы храним: хэш файла, id транзакции, комментарий, закодированный op_return, дата и время регистрации
	# в каком виде мы это будем хранить: храним в одну строчку разделенную табом, а последним полем обязательно должен быть комментарий
	fieldnames = ['hashid', 'transid', 'time', 'op_return', 'block', 'comment']

	with open('info.txt', 'r') as file:
        	records = file.readlines()

	result = {}

	for record in records:
		try:
			record = record.rstrip('\n')
			fields = record.split('\t', len(fieldnames) - 1)
			if len(fields) != len(fieldnames): continue
			
			sys.stderr.write(f"{fields[0]} vs {hashid}\n")
			if fields[0] == hashid:
				result = {fieldnames[i] : fields[i] for i in range(len(fields))}
				break
		except Exception as e:
			sys.stderr.write("cannot parse: " + str(record) + "\n" + str(e) + "\n")
			pass

	print("Content-Type: text/plain")
	print("")
	print(json.dumps(result))

except Exception as e:

	print("Content-Type: text/plain")
	print("")
	print("error: " + str(e))

